apiVersion: v1
kind: Service
metadata:
  name: youtube-backend-service
  namespace: youtube
spec:
  type: ClusterIP
  selector:
    app: youtube-backend
  ports:
    - port: 80
      targetPort: 5000
