apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-clone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: youtube-clone
  template:
    metadata:
      labels:
        app: youtube-clone
    spec:
      containers:
        - name: youtube-clone
          image: <ACCOUNT_ID>.dkr.ecr.ap-south-1.amazonaws.com/youtube-clone:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always
